### PR TITLE
Update sentence diagrams to figma versions

### PR DESCRIPTION
**Pull request by malcolmbarrett**
@LucyMcGowan what do you think about this tweak to the sentence diagrams? I started updating the ggplot versions but found them a bit fragile. I made these on figma so I can share that with you if you like them

### CODE REVIEW

**Comment by LucyMcGowan** [comment]
I am on the fence I totally agree that ggplot is not a good option but I want to do something that we can code in instead of hard coding in pngs that we have to update by hand

**Comment by malcolmbarrett** [comment]
That would be ideal, but for what it's worth, I managed to do this pretty quickly, and Figma is pretty good about having files accessible

**Comment by malcolmbarrett** [comment]
Maybe we should just cross that bridge when we come to it, e.g. if we find ourselves needing to update it, we find another code-based option (or at least something less manual)

**Comment by LucyMcGowan** [comment]
ok! the issue for me is when I am using the material to make slides it is less of a pain for me to copy the bad ggplot code into a slide than to have to figure out where the file is and copy it in but this might just be a personal preference! I am fine with merging this though 😂

**Comment by malcolmbarrett** [comment]
Hm one solution to that is to use the URL to the image on the rendered book directly in the slides so that they'll keep in sync whenever it's modified in the book. Then you don't need to manage a second+ file

**Comment by malcolmbarrett** [comment]
I'm going to merge but if we find a better solution happy to switch!

**Comment by LucyMcGowan** [comment]
See this is why we need you, just linking the url is brilliant!!

**Pull request merged**
