### PR TITLE
Not just a stats problem

### LINKED ISSUE #136: Expand on variable selection
- [ ] add c1, c2, c3 example + correlation to m-bias example. Checking the correlation of c1 with x and y doesn't work if those correlations are themselves confounded by c2 and 3

### LINKED ISSUE #149: Lucy's quartet
To help explain why DAGs are necessary

### LINKED ISSUE #217: 06.2 Causal and Predictive Models, Revisited

### LINKED ISSUE #218: 06.1 Causal inference is not (just) a statistical problem

### PR DESCRIPTION
**Pull request by malcolmbarrett**
Closes #149 
Closes #218 
Closes #217 
Closes #136

### CODE REVIEW

**Comment by malcolmbarrett** [comment]
@tgerke and @LucyMcGowan, this chapter is ready for your review!

**Comment by LucyMcGowan** [comment]
As we chatted about today, we could scale the variables for Fig 6.4 so that the slope is the same as the correlation. In a pop-over you can have the unscaled version with a little info about how the two are related.

**Review by LucyMcGowan — CHANGES_REQUESTED** [review]
As we chatted about today, we could scale the variables for Fig 6.4 so that the slope is the same as the correlation. In a pop-over you can have the unscaled version with a little info about how the two are related.

**Review by LucyMcGowan — APPROVED** [review]
looks great!

**Pull request merged**
